from pydantic import BaseModel, ConfigDict, Field, EmailStr
from datetime import datetime


class UserBase(BaseModel):
    username : str = Field(min_length=1, max_length=50)
    email : EmailStr = Field(max_length=120)
    
class UserCreate(UserBase):
    pass

class UserResponse(UserBase):
    model_config = ConfigDict(from_attributes=True)

    id : int
    image_file : str | None
    image_path : str


# This is the base model for a post, which includes the common fields that are shared between the create and response models. It uses Pydantic's Field function to specify validation rules for each field, such as minimum and maximum length.
class PostBase(BaseModel):
    title : str = Field(min_length=1,max_length=100 )
    content : str = Field(min_length=1)

# This is the model for creating a new post. It inherits from PostBase and doesn't add any new fields, but it can be used to validate the input data when creating a new post.
class PostCreate(PostBase):
    user_id : int # Temporary.


# This is the model for the response when retrieving a post. It inherits from PostBase and adds additional fields such as id and date_posted, which are typically generated by the server when a new post is created. The model_config with from_attributes=True allows Pydantic to create an instance of PostResponse from an object that has attributes matching the field names, which can be useful when working with ORM models or other data sources.
class PostResponse(PostBase):
    model_config = ConfigDict(from_attributes=True) # This allows Pydantic to create an instance of PostResponse from an object that has attributes matching the field names, which can be useful when working with ORM models or other data sources.

    id : int
    user_id : int
    date_posted : datetime
    author : UserResponse